name: Test Action
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get yamllint version
        run: yamllint --version

      - id: lint-with-config
        name: lint with config
        uses: ./
        with:
          file_or_dir: test
          config_data: |
            extends: default
            ignore: nok.yaml
            rules:
              new-line-at-end-of-file:
                level: warning
              trailing-spaces:
                level: warning

      - id: lint-all-no-warnings
        name: lint all - no warnings (continue on error)
        continue-on-error: true
        uses: ./
        with:
          file_or_dir: test
          strict: true
          no_warnings: true

      - id: lint-all-continue
        name: lint all (continue on error)
        continue-on-error: true
        uses: ./
        with:
          file_or_dir: test
          strict: true
          format: standard

      - id: default-lint-all
        name: default lint all (continue on error)
        continue-on-error: true
        uses: ./

      - id: print-output
        if: always()
        name: Print output
        run: |
          echo ${{ steps.lint-with-config.outputs.logfile }}
          cat ${{ steps.lint-with-config.outputs.logfile }}

          echo ${{ steps.lint-all-continue.outputs.logfile }}
          cat ${{ steps.lint-all-continue.outputs.logfile }}
